# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyssh < Formula
  desc "A simple terminal UI for managing SSH connections.  "
  homepage "https://github.com/adembc/lazyssh"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.2.0/lazyssh_Darwin_x86_64.tar.gz"
      sha256 "5e2b5b60093ba331336f1248b63fb897e17cc72e6f371117010be10ee5d9cc0d"

      def install
        bin.install "lazyssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.2.0/lazyssh_Darwin_arm64.tar.gz"
      sha256 "951f7a4300b016681ed96b57c9089fd731af267cce14d8c366d76cee7a855461"

      def install
        bin.install "lazyssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.2.0/lazyssh_Linux_x86_64.tar.gz"
      sha256 "ca8176906ed7281e023f045c0f69ca8ee5579d99e2777b748483ddab117aef17"
      def install
        bin.install "lazyssh"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.2.0/lazyssh_Linux_armv6.tar.gz"
      sha256 "c85a8c2db91044f93a385595dbb5fbea261fe5424a123f6029e1f9980625ac6c"
      def install
        bin.install "lazyssh"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.2.0/lazyssh_Linux_arm64.tar.gz"
      sha256 "04a9de5f21d3578eca78a7ca894818e411925a62dbafb43f32525909039388d1"
      def install
        bin.install "lazyssh"
      end
    end
  end
end
