# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyssh < Formula
  desc "A simple terminal UI for managing SSH connections."
  homepage "https://github.com/adembc/lazyssh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.1.0/lazyssh_Darwin_x86_64.tar.gz"
      sha256 "8e6aca91b14c080c33ecfd09c98f138b9e0e612a5f5c8bc9f5970d0b5b7a7261"

      def install
        bin.install "lazyssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.1.0/lazyssh_Darwin_arm64.tar.gz"
      sha256 "d6576b3644f2fb4b0b6ae598b56bdb7977f3b5e86ccb8329b38d406dab2cd235"

      def install
        bin.install "lazyssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.1.0/lazyssh_Linux_x86_64.tar.gz"
      sha256 "52671fb853bc99a6e0bf874b6b8b8f31975bbf68293eaccdb9027aef4df1fae9"
      def install
        bin.install "lazyssh"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.1.0/lazyssh_Linux_armv6.tar.gz"
      sha256 "c07c90d78661b2414bfb1d9391adc7526c188afe9a6fa26c5153aa6f8ee7813f"
      def install
        bin.install "lazyssh"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Adembc/lazyssh/releases/download/v0.1.0/lazyssh_Linux_arm64.tar.gz"
      sha256 "de018f7a75f5c048664f0eac0e37982ea2bc3ee45d622d5150129a718c2e6ca4"
      def install
        bin.install "lazyssh"
      end
    end
  end

  test do
    system "#{bin}/lazyssh", "--version"
  end
end
